spring.datasource.url=jdbc:postgresql://postgres:5432/rssb_bav
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/springboot-test
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://161.118.167.160:31457/realms/springboot-test
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/springboot-test/protocol/openid-connect/certs
keycloak.server-url=http://keycloak:8080
keycloak.realm=springboot-test
keycloak.client-id=spring-boot-backend
keycloak.client-secret=zruaVAUIso9BLwOTp3mZXSU774YTGwvc
keycloak.username=admin
keycloak.password=admin

app.keycloak.enabled=true
