#spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/rssb_bav
spring.datasource.url=jdbc:postgresql://localhost:5432/rssb_bav

spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#management.endpoints.web.exposure.include=*
#management.endpoints.web.exposure.include=httpexchanges

#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/rssb-realm
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8090/realms/rssb-realm/protocol/openid-connect/certs
#
#keycloak.base-url=http://localhost:8090
#keycloak.realm=rssb-realm
#keycloak.admin-client-id=rssb-java
#keycloak.admin-client-secret=J7Km4nboRrs9HJiViUtZw4oEIGmPUUHg
#app.frontend-url=http://localhost:3000

#spring.security.oauth2.client.registration.keycloak.client-id=rssb-java
#spring.security.oauth2.client.registration.keycloak.client-secret=J7Km4nboRrs9HJiViUtZw4oEIGmPUUHg
#spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
#spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:8082/login/oauth2/code/keycloak
#
#spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:14082/realms/rssb-realm

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:14082/realms/springboot-test

# Keycloak Configuration
keycloak.server-url=http://localhost:14082
keycloak.realm=springboot-test
keycloak.client-id=spring-boot-backend
keycloak.client-secret=O0lftNPUYpwZSlrq3SK1W9oRFbwvLSh1
keycloak.username=admin
keycloak.password=admin

# Application settings
app.keycloak.enabled=true






